### ISSUE TITLE
Support for generate Cap'n Proto text format file

### ISSUE THREAD

**Issue by VaalaCat** [capnproto/go-capnp#526]
I am currently working on a platform built with Cloudflare's Workers, which requires a Cap'n Proto text format configuration file. I would greatly appreciate the ability to generate this file from your Golang package. Thank you!

P.S. workerd: https://github.com/cloudflare/workerd

**Comment by zenhack** [comment]
I think the package `encoding/text` within this repository does what you want.

**Comment by VaalaCat** [comment]
This seems suitable for my needs. Great Thanks!
