### ISSUE TITLE
Log levels for error reporter

### ISSUE THREAD

**Issue by zenhack** [capnproto/go-capnp#535]
This has come up a couple times on matrix now: it would be nice to have something like log levels in ErrorReporter; in particular, here are a few things I'd like to be able to filter differently:

- Protocol errors
- Disconnects
- Soon, with 3PH: falling back to using a vine, when forming a direct connection fails

We could go all in and just accept a Logger from the new slog package: https://pkg.go.dev/golang.org/x/exp/slog#Logger

Though I worry this might bloat code size, which I want to avoid for the frontend code in tempest. We could also define an interface with the log levels we care about that Logger satisfies.

**Comment by philippgille** [comment]
Some related work seems to have been done already: https://github.com/capnproto/go-capnp/pull/537

**Comment by lthibault** [comment]
@philippgille Indeed.  I have to go through Ian's PR to see how much of this is covered by the addition of the logging interface.  I _think_ this issue might technically be resolved already.
