### ISSUE TITLE
Tag for alpha.29 has unexpected format

### ISSUE THREAD

**Issue by mologie** [capnproto/go-capnp#538]
This is super nitpicky, but I'd just like you to know that there is a typo in the latest v3 tag (which exists twice, also with a typo):

![image](https://github.com/capnproto/go-capnp/assets/597682/31aa4f6b-fd7b-4111-819a-ef4886d12c3b)

It's [a hyphen, then dots](https://go.dev/blog/publishing-go-modules) and was normal with all previous tags. (Can probably delete the bogus ones, it's alpha after all.)

**Comment by lthibault** [comment]
Oh wow, not nit-picky at all!  Fixed.  Thanks for letting us know.
