### ISSUE TITLE
zenhack.net is Gone

### ISSUE THREAD

**Issue by alrs** [capnproto/go-capnp#548]
The VPS behind `zenhack.net` is gone, so this project no longer builds with `GOPROXY=direct`.

I think it makes sense to fork https://github.com/zenhack/go-util to https://github.com/capnproto/zenhack-util, or to merge all of `go-util` into this project.

I've done this work here:
https://github.com/capnproto/go-capnp/pull/547

**Comment by alrs** [comment]
Alternately, since @lthibault has control of he original repo, I could alternately just change the imports to https://github.com/zenhack/go-util.

https://github.com/zenhack/go-util/pull/8

**Comment by lthibault** [comment]
I'm generally in favor of moving `zenhack.net/go/util` into this repo.  I'm aiming to review #547 later today.

**Comment by arlyon** [comment]
do you intend to release a new version? right now nobody can install this library.

**Comment by lthibault** [comment]
@arlyon Have you tried `go get -u capnproto.org/go/capnp/v3@main`?  That ought to install the latest commit.  Please let me know if this is not a sufficient short-term solution.

To answer your question:  the intent is to release a new version as soon as we are able to fix the regressions in the `main` branch.  We are currently dealing with a situation in which one of the maintainers has passed away, so we're having to juggle quite a few things (in addition to our day jobs).  If you are able to contribute code, that would definitely be the fastest path forward, and would be more than happy to provide high-touch/hands-on support for that 🙂

**Comment by lthibault** [comment]
No worries -- I definitely didn't take it as criticism 😃 

Here are what I consider to be the major blockers for cutting a new release.  If you have a chance to investigate any of these, it would be an _enormous_ help 🙏 

- https://github.com/capnproto/go-capnp/issues/543
- https://github.com/capnproto/go-capnp/issues/521
- https://github.com/capnproto/go-capnp/issues/377
