### ISSUE TITLE
Unable to install go-capnp

### ISSUE THREAD

**Issue by homier** [capnproto/go-capnp#557]
Hi everyone,

Installing the project via `go install` results in the following error:
```bash
go install capnproto.org/go/capnp/v3/capnpc-go@latest
go: downloading zenhack.net/go/util v0.0.0-20230414204917-531d38494cf5
.go/pkg/mod/capnproto.org/go/capnp/v3@v3.0.0-alpha.30/answer.go:10:2: unrecognized import path "zenhack.net/go/util": https fetch: Get "https://zenhack.net/go/util?go-get=1": dial tcp 45.130.21.147:443: i/o timeout
```
I've been getting this error for 2 days in a row, so clearly the dependency is broken.

Although I understand that I can use cache proxy to prevent this, it's quite annoying to have broken dependencies.

**Comment by lthibault** [comment]
@homier Yes, we've had a core dev pass away unexpectedly and his domain has since expired.  I don't have any dev cycles available right now, but the fix should be a pretty straightforward matter of adding the dependencies under the `zenhack.net` domain to the present repo as subpackages.  Would you be willing to submit a PR?

**Comment by homier** [comment]
@lthibault I've found this pull request #547, that already does the work. Will you be able to merge it, or it requires some more work? 

Thanks

**Comment by homier** [comment]
@lthibault I've found this pull request #547 was merged into the main branch a few months ago. Will you be able to submit a new release that includes this fix? 

Thanks :)

P.S. What's the status of the library in general? I'd like to use capnp in my project, and I'm not really sure, whether it's in development or not.

**Comment by ocdtrekkie** [comment]
Multiple projects use go-capnp as a core dependency, it will be a bit slow development-wise for a bit but is safe to use knowing it will be supported in the future. capnproto as a whole is now a critical part of Cloudflare's infrastructure and will be well-supported and maintained for an extremely long time.

**Comment by homier** [comment]
@ocdtrekkie thanks for the reply! That brings a lot of hope :)

I guess the issue should be open until a new release is published, so I won't close it for now.

P.S. Sorry for the late answer

**Comment by cmackenzie1** [comment]
Hey folks, the latest version (`v3.0.1-alpha.1`) has been released and no longer references the expired domain. 

https://github.com/capnproto/go-capnp/releases/tag/v3.0.1-alpha.1

**Comment by lthibault** [comment]
Thanks for covering this @cmackenzie1 !

Closing
