### ISSUE TITLE
Tooling reports latest alpha version as outdated, v3.0.0-alpha-29 as current

### ISSUE THREAD

**Issue by mologie** [capnproto/go-capnp#558]
Due to #538, tooling such as Jetbrains GoLand, go-mod-update, etc. currently show `v3.0.0-alpha-29` as latest version because it is lexicographical higher than `v3.0.0-alpha.30`.

Unfortunately it's not possible to [retract](https://go.dev/ref/mod#go-mod-file-retract) the version either because of the following condition in go.mod:

> To retract a version, a module author should add a retract directive to go.mod, then publish a new version containing that directive. The new version must be higher than other release or pre-release versions; that is, the latest [version query](https://go.dev/ref/mod#version-queries) should resolve to the new version before retractions are considered.

A future version will have to be published as v3.0.0-beta or v3.0.1-alpha to fix update checks in most go tooling.

**Comment by cmackenzie1** [comment]
Hey @mologie, version `v3.0.1-alpha.1` has been released and should reflect correctly in GoLand now!

https://github.com/capnproto/go-capnp/releases/tag/v3.0.1-alpha.1

**Comment by mologie** [comment]
It does, thank you for the heads-up!
