### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by Jumpmanhere** [capnproto/go-capnp#570]
https://capnproto.org/install.html 

 Hi, I am following the installing steps but failed at "make -j6 check". 

The error is "~/setup_capprotogo/capnproto-c++-1.0.2/.libs/lt-capnp: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ~/setup_capprotogo/capnproto-c++-1.0.2/.libs/libkj-1.0.2.so)
" 
looking forward to the suggestions

**Comment by lthibault** [comment]
Hello, I believe this would be an issue for https://github.com/capnproto/capnproto.

Closing (thanks for posting this nonetheless 🙂!)
