### ISSUE TITLE
Default nopLimiter behavior is a footgun when a vat becomes unresponsive

### ISSUE THREAD

**Issue by ObsidianMinor** [capnproto/go-capnp#571]
Title.

In the event a vat is unresponsive it's very easy to accidentally footgun yourself with the default FlowLimiter. Since the flow is unlimited, you can very easily accumulate tons of GBs of buffer memory, go objects, and goroutines on accident because you forgot to instantiate a flow limiter.

A better default behavior to prevent footguns should be to match the old behavior that clients did before streaming was introduced: one call allowed at a time. This would be much slower, but you can't shoot yourself in the foot with it on accident by forgetting to add a flow limiter.

The current nopLimiter behavior can be relegated to a separate "unlimited" type so users are aware of the behavior of the type.

**Comment by lthibault** [comment]
We're aware of the issue.  Resource exhaustion is a really tricky thing to tackle in the general case, and I am strongly biased towards "simpler is better", which in this case would be "let her rip".  Note that this is consistent with the behavior of most HTTP/RPC systems, which do not attempt to throttle outstanding requests and will happily allow a process to OOM.

Really, I'd expect most devs to consider rate-limiting before putting software in prod.  I know this isn't the answer you were hoping for, but I'm closing for now, unless there's something else that I've overlooked.  On the plus side, current plan is/was to add a field to `rpc.Options` allowing the receiver to specify a maximum number of outstanding calls (and/or perhaps total aggregate message size) beyond which to error out and cut the connection.  ETA unknown.

Thank you for opening this issue nonetheless! 🙂 

(@davidhubbard do you feel strongly one way or another?)

**Comment by davidhubbard** [comment]
I feel strongly along the same lines as @lthibault, that RPC systems don't have any default limit. This is the nopLimiter.
