### ISSUE TITLE
Breaking API change with 3.0.1-alpha.1

### ISSUE THREAD

**Issue by bserdar** [capnproto/go-capnp#573]
Version 3.0.1-alpha.1 is not compatible with 3.0.0-alpha-29. Changes to rpc/Options are not compatible.

3.0.0-alpha-29: https://pkg.go.dev/capnproto.org/go/capnp/v3@v3.0.0-alpha.29/rpc#Options
3.0.1-alpha-1: https://pkg.go.dev/capnproto.org/go/capnp/v3@v3.0.1-alpha.1/rpc#Options

ErrorReporter is changed to Logger.

**Comment by lthibault** [comment]
Correct, this is still alpha software and breaking changes are expected.
